version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    image: apksneeze_web
    container_name: apksneeze_web
    env_file: ./.env/.postgres
    ports:
      - "5000:5000"
    volumes:
      - "./flask/:/flask/"
      - "./storage:/storage"
    depends_on:
      - redis
      - postgres
    
  worker:
    build:
      context: .
      dockerfile: ./compose/worker/Dockerfile
    image: apksneeze_worker
    container_name: apksneeze_worker
    env_file: ./.env/.postgres
    volumes:
      - "./storage:/storage"
    depends_on:
      - flask
      - redis
      - postgres

  redis:
    image: redis:6.0.6-buster
    container_name: apksneeze_redis
  
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    container_name: apksneeze_db
    env_file: ./.env/.postgres