version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    image: apksneeze_web
    container_name: apksneeze_web
    env_file: ./.env/.postgres
    ports:
      - "5000:5000"
    volumes:
      - "./app/src:/flask/app"
      - "./app/storage:/storage"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:6.0.6-buster
    container_name: redis
  
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    container_name: apksneeze_db
    env_file: ./.env/.postgres